

#' List Models
#'
#' Lists the currently available models, and provides basic information about each one such as the owner and availability.
#'
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/models/list}{Open AI Documentation}
#' @export
list_models <- function(return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/models')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Retrieve Model
#'
#' Retrieves a model instance, providing basic information about the model such as the owner and permissioning.
#'
#' @param model (string) The ID of the model to use for this request Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/models/retrieve}{Open AI Documentation}
#' @export
retrieve_model <- function(model, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/models/{model}')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Completion
#'
#' Creates a completion for the provided prompt and parameters
#'
#' @param model (string) ID of the model to use. You can use the List models API to see all of your available models, or see our Model overview for descriptions of them. Required
#' @param best_of (integer) Generates best_of completions server-side and returns the "best" (the one with the highest log probability per token). Results cannot be streamed. When used with n, best_of controls the number of candidate completions and n specifies how many to return – best_of must be greater than n. Note: Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for max_tokens and stop. 
#' @param echo (boolean) Echo back the prompt in addition to the completion 
#' @param frequency_penalty (number) Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim. See more information about frequency and presence penalties. 
#' @param logit_bias (map) Modify the likelihood of specified tokens appearing in the completion. Accepts a json object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this tokenizer tool (which works for both GPT-2 and GPT-3) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token. As an example, you can pass {"50256": -100} to prevent the <|endoftext|> token from being generated. 
#' @param logprobs (integer) Include the log probabilities on the logprobs most likely tokens, as well the chosen tokens. For example, if logprobs is 5, the API will return a list of the 5 most likely tokens. The API will always return the logprob of the sampled token, so there may be up to logprobs+1 elements in the response. The maximum value for logprobs is 5. If you need more than this, please contact us through our Help center and describe your use case. 
#' @param max_tokens (integer) The maximum number of tokens to generate in the completion. The token count of your prompt plus max_tokens cannot exceed the model's context length. Most models have a context length of 2048 tokens (except for the newest models, which support 4096). 
#' @param n (integer) How many completions to generate for each prompt. Note: Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for max_tokens and stop. 
#' @param presence_penalty (number) Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics. See more information about frequency and presence penalties. 
#' @param prompt (string or array) The prompt(s) to generate completions for, encoded as a string, array of strings, array of tokens, or array of token arrays. Note that <|endoftext|> is the document separator that the model sees during training, so if a prompt is not specified the model will generate as if from the beginning of a new document. 
#' @param stop (string or array) Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence. 
#' @param stream (boolean) Whether to stream back partial progress. If set, tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a data: [DONE] message. 
#' @param suffix (string) The suffix that comes after a completion of inserted text. 
#' @param temperature (number) What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both. 
#' @param top_p (number) An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both. 
#' @param user (string) A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. Learn more. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/completions/create}{Open AI Documentation}
#' @export
create_completion <- function(model, best_of = NULL, echo = NULL, frequency_penalty = NULL, logit_bias = NULL, logprobs = NULL, max_tokens = NULL, n = NULL, presence_penalty = NULL, prompt = NULL, stop = NULL, stream = NULL, suffix = NULL, temperature = NULL, top_p = NULL, user = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/completions')

	body_params <- c("model","best_of","echo","frequency_penalty","logit_bias","logprobs","max_tokens","n","presence_penalty","prompt","stop","stream","suffix","temperature","top_p","user")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Chat Completion - Beta
#'
#' Creates a completion for the chat message
#'
#' @param messages (array) The messages to generate chat completions for, in the chat format. Required
#' @param model (string) ID of the model to use. See the model endpoint compatibility table for details on which models work with the Chat API. Required
#' @param frequency_penalty (number) Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim. See more information about frequency and presence penalties. 
#' @param logit_bias (map) Modify the likelihood of specified tokens appearing in the completion. Accepts a json object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token. 
#' @param max_tokens (integer) The maximum number of tokens to generate in the chat completion. The total length of input tokens and generated tokens is limited by the model's context length. 
#' @param n (integer) How many chat completion choices to generate for each input message. 
#' @param presence_penalty (number) Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics. See more information about frequency and presence penalties. 
#' @param stop (string or array) Up to 4 sequences where the API will stop generating further tokens. 
#' @param stream (boolean) If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a data: [DONE] message. See the OpenAI Cookbook for example code. 
#' @param temperature (number) What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both. 
#' @param top_p (number) An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both. 
#' @param user (string) A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. Learn more. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/chat/create}{Open AI Documentation}
#' @export
create_chat_completion <- function(messages, model, frequency_penalty = NULL, logit_bias = NULL, max_tokens = NULL, n = NULL, presence_penalty = NULL, stop = NULL, stream = NULL, temperature = NULL, top_p = NULL, user = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/chat/completions')

	body_params <- c("messages","model","frequency_penalty","logit_bias","max_tokens","n","presence_penalty","stop","stream","temperature","top_p","user")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Edit
#'
#' Creates a new edit for the provided input, instruction, and parameters.
#'
#' @param instruction (string) The instruction that tells the model how to edit the prompt. Required
#' @param model (string) ID of the model to use. You can use the text-davinci-edit-001 or code-davinci-edit-001 model with this endpoint. Required
#' @param input (string) The input text to use as a starting point for the edit. 
#' @param n (integer) How many edits to generate for the input and instruction. 
#' @param temperature (number) What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both. 
#' @param top_p (number) An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/edits/create}{Open AI Documentation}
#' @export
create_edit <- function(instruction, model, input = NULL, n = NULL, temperature = NULL, top_p = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/edits')

	body_params <- c("instruction","model","input","n","temperature","top_p")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Image - Beta
#'
#' Creates an image given a prompt.
#'
#' @param prompt (string) A text description of the desired image(s). The maximum length is 1000 characters. Required
#' @param n (integer) The number of images to generate. Must be between 1 and 10. 
#' @param response_format (string) The format in which the generated images are returned. Must be one of url or b64_json. 
#' @param size (string) The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. 
#' @param user (string) A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. Learn more. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/images/create}{Open AI Documentation}
#' @export
create_image <- function(prompt, n = NULL, response_format = NULL, size = NULL, user = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/images/generations')

	body_params <- c("prompt","n","response_format","size","user")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Image Edit - Beta
#'
#' Creates an edited or extended image given an original image and a prompt.
#'
#' @param image (string) The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask. Required
#' @param prompt (string) A text description of the desired image(s). The maximum length is 1000 characters. Required
#' @param mask (string) An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as image. 
#' @param n (integer) The number of images to generate. Must be between 1 and 10. 
#' @param response_format (string) The format in which the generated images are returned. Must be one of url or b64_json. 
#' @param size (string) The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. 
#' @param user (string) A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. Learn more. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/images/create-edit}{Open AI Documentation}
#' @export
create_image_edit <- function(image, prompt, mask = NULL, n = NULL, response_format = NULL, size = NULL, user = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/images/edits')

	body_params <- c("image","prompt","mask","n","response_format","size","user")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Image Variation - Beta
#'
#' Creates a variation of a given image.
#'
#' @param image (string) The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square. Required
#' @param n (integer) The number of images to generate. Must be between 1 and 10. 
#' @param response_format (string) The format in which the generated images are returned. Must be one of url or b64_json. 
#' @param size (string) The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024. 
#' @param user (string) A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. Learn more. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/images/create-variation}{Open AI Documentation}
#' @export
create_image_variation <- function(image, n = NULL, response_format = NULL, size = NULL, user = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/images/variations')

	body_params <- c("image","n","response_format","size","user")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Embeddings
#'
#' Creates an embedding vector representing the input text.
#'
#' @param input (string or array) Input text to get embeddings for, encoded as a string or array of tokens. To get embeddings for multiple inputs in a single request, pass an array of strings or array of token arrays. Each input must not exceed 8192 tokens in length. Required
#' @param model (string) ID of the model to use. You can use the List models API to see all of your available models, or see our Model overview for descriptions of them. Required
#' @param user (string) A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. Learn more. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/embeddings/create}{Open AI Documentation}
#' @export
create_embeddings <- function(input, model, user = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/embeddings')

	body_params <- c("input","model","user")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Transcription - Beta
#'
#' Transcribes audio into the input language.
#'
#' @param file (string) The audio file to transcribe, in one of these formats: mp3, mp4, mpeg, mpga, m4a, wav, or webm. Required
#' @param model (string) ID of the model to use. Only whisper-1 is currently available. Required
#' @param language (string) The language of the input audio. Supplying the input language in ISO-639-1 format will improve accuracy and latency. 
#' @param prompt (string) An optional text to guide the model's style or continue a previous audio segment. The prompt should match the audio language. 
#' @param response_format (string) The format of the transcript output, in one of these options: json, text, srt, verbose_json, or vtt. 
#' @param temperature (number) The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use log probability to automatically increase the temperature until certain thresholds are hit. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/audio/create}{Open AI Documentation}
#' @export
create_transcription <- function(file, model, language = NULL, prompt = NULL, response_format = NULL, temperature = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/audio/transcriptions')

	body_params <- c("file","model","language","prompt","response_format","temperature")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	body$file <- httr::upload_file(body$file)

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'multipart', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Translation - Beta
#'
#' Translates audio into into English.
#'
#' @param file (string) The audio file to translate, in one of these formats: mp3, mp4, mpeg, mpga, m4a, wav, or webm. Required
#' @param model (string) ID of the model to use. Only whisper-1 is currently available. Required
#' @param prompt (string) An optional text to guide the model's style or continue a previous audio segment. The prompt should be in English. 
#' @param response_format (string) The format of the transcript output, in one of these options: json, text, srt, verbose_json, or vtt. 
#' @param temperature (number) The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use log probability to automatically increase the temperature until certain thresholds are hit. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/audio/create}{Open AI Documentation}
#' @export
create_translation <- function(file, model, prompt = NULL, response_format = NULL, temperature = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/audio/translations')

	body_params <- c("file","model","prompt","response_format","temperature")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	body$file <- httr::upload_file(body$file)

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'multipart', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' List Files
#'
#' Returns a list of files that belong to the user's organization.
#'
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/files/list}{Open AI Documentation}
#' @export
list_files <- function(return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/files')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Upload File
#'
#' Upload a file that contains document(s) to be used across various endpoints/features. Currently, the size of all the files uploaded by one organization can be up to 1 GB. Please contact us if you need to increase the storage limit.
#'
#' @param file (string) Name of the JSON Lines file to be uploaded. If the purpose is set to "fine-tune", each line is a JSON record with "prompt" and "completion" fields representing your training examples. Required
#' @param purpose (string) The intended purpose of the uploaded documents. Use "fine-tune" for Fine-tuning. This allows us to validate the format of the uploaded file. Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/files/upload}{Open AI Documentation}
#' @export
upload_file <- function(file, purpose, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/files')

	body_params <- c("file","purpose")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	body$file <- httr::upload_file(body$file)

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'multipart', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Delete File
#'
#' Delete a file.
#'
#' @param file_id (string) The ID of the file to use for this request Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/files/delete}{Open AI Documentation}
#' @export
delete_file <- function(file_id, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/files/{file_id}')

	body <- NULL

	query <- NULL

	response <- httr::DELETE(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Retrieve File
#'
#' Returns information about a specific file.
#'
#' @param file_id (string) The ID of the file to use for this request Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/files/retrieve}{Open AI Documentation}
#' @export
retrieve_file <- function(file_id, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/files/{file_id}')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Retrieve File Content
#'
#' Returns the contents of the specified file
#'
#' @param file_id (string) The ID of the file to use for this request Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/files/retrieve-content}{Open AI Documentation}
#' @export
retrieve_file_content <- function(file_id, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/files/{file_id}/content')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Fine-Tune
#'
#' Creates a job that fine-tunes a specified model from a given dataset.
#'
#' @param training_file (string) The ID of an uploaded file that contains training data. See upload file for how to upload a file. Your dataset must be formatted as a JSONL file, where each training example is a JSON object with the keys "prompt" and "completion". Additionally, you must upload your file with the purpose fine-tune. See the fine-tuning guide for more details. Required
#' @param batch_size (integer) The batch size to use for training. The batch size is the number of training examples used to train a single forward and backward pass. By default, the batch size will be dynamically configured to be ~0.2% of the number of examples in the training set, capped at 256 - in general, we've found that larger batch sizes tend to work better for larger datasets. 
#' @param classification_betas (array) If this is provided, we calculate F-beta scores at the specified beta values. The F-beta score is a generalization of F-1 score. This is only used for binary classification. With a beta of 1 (i.e. the F-1 score), precision and recall are given the same weight. A larger beta score puts more weight on recall and less on precision. A smaller beta score puts more weight on precision and less on recall. 
#' @param classification_n_classes (integer) The number of classes in a classification task. This parameter is required for multiclass classification. 
#' @param classification_positive_class (string) The positive class in binary classification. This parameter is needed to generate precision, recall, and F1 metrics when doing binary classification. 
#' @param compute_classification_metrics (boolean) If set, we calculate classification-specific metrics such as accuracy and F-1 score using the validation set at the end of every epoch. These metrics can be viewed in the results file. In order to compute classification metrics, you must provide a validation_file. Additionally, you must specify classification_n_classes for multiclass classification or classification_positive_class for binary classification. 
#' @param learning_rate_multiplier (number) The learning rate multiplier to use for training. The fine-tuning learning rate is the original learning rate used for pretraining multiplied by this value. By default, the learning rate multiplier is the 0.05, 0.1, or 0.2 depending on final batch_size (larger learning rates tend to perform better with larger batch sizes). We recommend experimenting with values in the range 0.02 to 0.2 to see what produces the best results. 
#' @param model (string) The name of the base model to fine-tune. You can select one of "ada", "babbage", "curie", "davinci", or a fine-tuned model created after 2022-04-21. To learn more about these models, see the Models documentation. 
#' @param n_epochs (integer) The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. 
#' @param prompt_loss_weight (number) The weight to use for loss on the prompt tokens. This controls how much the model tries to learn to generate the prompt (as compared to the completion which always has a weight of 1.0), and can add a stabilizing effect to training when completions are short. If prompts are extremely long (relative to completions), it may make sense to reduce this weight so as to avoid over-prioritizing learning the prompt. 
#' @param suffix (string) A string of up to 40 characters that will be added to your fine-tuned model name. For example, a suffix of "custom-model-name" would produce a model name like ada:ft-your-org:custom-model-name-2022-02-15-04-21-04. 
#' @param validation_file (string) The ID of an uploaded file that contains validation data. If you provide this file, the data is used to generate validation metrics periodically during fine-tuning. These metrics can be viewed in the fine-tuning results file. Your train and validation data should be mutually exclusive. Your dataset must be formatted as a JSONL file, where each validation example is a JSON object with the keys "prompt" and "completion". Additionally, you must upload your file with the purpose fine-tune. See the fine-tuning guide for more details. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/fine-tunes/create}{Open AI Documentation}
#' @export
create_fine_tune <- function(training_file, batch_size = NULL, classification_betas = NULL, classification_n_classes = NULL, classification_positive_class = NULL, compute_classification_metrics = NULL, learning_rate_multiplier = NULL, model = NULL, n_epochs = NULL, prompt_loss_weight = NULL, suffix = NULL, validation_file = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/fine-tunes')

	body_params <- c("training_file","batch_size","classification_betas","classification_n_classes","classification_positive_class","compute_classification_metrics","learning_rate_multiplier","model","n_epochs","prompt_loss_weight","suffix","validation_file")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' List Fine-Tunes
#'
#' List your organization's fine-tuning jobs
#'
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/fine-tunes/list}{Open AI Documentation}
#' @export
list_fine_tunes <- function(return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/fine-tunes')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Retrieve Fine-Tune
#'
#' Gets info about the fine-tune job.
#'
#' @param fine_tune_id (string) The ID of the fine-tune job Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/fine-tunes/retrieve}{Open AI Documentation}
#' @export
retrieve_fine_tune <- function(fine_tune_id, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/fine-tunes/{fine_tune_id}')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Cancel Fine-Tune
#'
#' Immediately cancel a fine-tune job.
#'
#' @param fine_tune_id (string) The ID of the fine-tune job to cancel Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/fine-tunes/cancel}{Open AI Documentation}
#' @export
cancel_fine_tune <- function(fine_tune_id, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/fine-tunes/{fine_tune_id}/cancel')

	body <- NULL

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' List Fine-Tune Events
#'
#' Get fine-grained status updates for a fine-tune job.
#'
#' @param fine_tune_id (string) The ID of the fine-tune job to get events for. Required
#' @param stream (boolean) Whether to stream events for the fine-tune job. If set to true, events will be sent as data-only server-sent events as they become available. The stream will terminate with a data: [DONE] message when the job is finished (succeeded, cancelled, or failed). If set to false, only events generated so far will be returned. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/fine-tunes/events}{Open AI Documentation}
#' @export
list_fine_tune_events <- function(fine_tune_id, stream = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/fine-tunes/{fine_tune_id}/events')

	body <- NULL

	query_params <- c("stream")
	query <- query_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(query_params) %>% purrr::compact()

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Delete Fine-Tune Model
#'
#' Delete a fine-tuned model. You must have the Owner role in your organization.
#'
#' @param model (string) The model to delete Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/fine-tunes/delete-model}{Open AI Documentation}
#' @export
delete_fine_tune_model <- function(model, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/models/{model}')

	body <- NULL

	query <- NULL

	response <- httr::DELETE(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Create Moderation
#'
#' Classifies if text violates OpenAI's Content Policy
#'
#' @param input (string or array) The input text to classify Required
#' @param model (string) Two content moderations models are available: text-moderation-stable and text-moderation-latest. The default is text-moderation-latest which will be automatically upgraded over time. This ensures you are always using our most accurate model. If you use text-moderation-stable, we will provide advanced notice before updating the model. Accuracy of text-moderation-stable may be slightly lower than for text-moderation-latest. 
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/moderations/create}{Open AI Documentation}
#' @export
create_moderation <- function(input, model = NULL, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/moderations')

	body_params <- c("input","model")
	body <- body_params %>% purrr::map(~ eval(parse(text = .x))) %>% stats::setNames(body_params) %>% purrr::compact()

	query <- NULL

	response <- httr::POST(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' List Enginesdeprecated
#'
#' Lists the currently available (non-finetuned) models, and provides basic information about each one such as the owner and availability.
#'
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/engines/list}{Open AI Documentation}
#' @export
list_enginesdeprecated <- function(return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/engines')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}



#' Retrieve Enginedeprecated
#'
#' Retrieves a model instance, providing basic information about it such as the owner and availability.
#'
#' @param engine_id (string) The ID of the engine to use for this request Required
#' @param return_response (boolean) Whether to return the API response or parse the contents of the response. Defaults to FALSE (parse the response).
#' @seealso \href{https://platform.openai.com/docs/api-reference/engines/retrieve}{Open AI Documentation}
#' @export
retrieve_enginedeprecated <- function(engine_id, return_response = F){

	check_authentication()

	endpoint_url <- glue::glue('https://api.openai.com/v1/engines/{engine_id}')

	body <- NULL

	query <- NULL

	response <- httr::GET(url = endpoint_url, body = body, encode = 'json', query = query, httr::add_headers(`OpenAI-Organization` = Sys.getenv("openai_organization_id"), Authorization = glue::glue('Bearer {Sys.getenv("openai_secret_key")}')))

	if(return_response) return(response)

	parse_response(response)

}




